data_path: src/ml_project/assets/raw/heart_cleveland_upload.csv
expname: experiment
features:
  categorical_features_max_uniqs: 5
  create_dummy: true
  features_to_drop: null
  numeric_features_min_uniqs: 5
  scaler: MinMaxScaler
  target_col: condition
  use_scaler: true
mlflow_exp: mlops
mlflow_url: null
model:
  kwargs_path: null
  last_model: runs:/e3fa174b828842bba47c688e584c4402/LogisticRegression_experiment
  model_name: LogisticRegression
  module: sklearn
  save_as: null
  submodule: linear_model
s3:
  bucket: dvcstorage
  defaultfile: heart_cleveland_upload.csv
  defaultout: src/ml_project/assets/raw
  path: untracked
splitting:
  random_state: 42
  val_size: 0.3
use_mlflow: true
