name: Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: python:3.9.6-slim
    name: Lint
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Install linter dependencies and package
        run: pip install .[dev]

      - name: flake8 Lint
        uses: py-actions/flake8@v2
